<map id="openage::error::Error::rethrow_cause" name="openage::error::Error::rethrow_cause">
<area shape="rect" id="node2" href="$d1/d18/namespaceopenage_1_1pyinterface_1_1tests.xhtml#a1e06395c26a8fbab8f488d6e573cde6b" title="openage::pyinterface\l::tests::err_py_to_cpp" alt="" coords="208,5,357,47"/>
<area shape="rect" id="node3" href="$db/dbd/namespaceopenage_1_1error.xhtml#a902be6cbbea4f6485907cc5e15406b3a" title="openage::error::operator\&lt;\&lt;" alt="" coords="195,71,371,98"/>
</map>
